---
- name: サービス型NGINXの証明書更新
  include_tasks: service_nginx.yml
  when: nginx_daemon_type == 'service'

- name: コンテナ型NGINXの証明書更新
  include_tasks: docker_nginx.yml
  when: nginx_daemon_type == 'docker'
