---
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/repo

    steps:
      - checkout
      - run: sudo pip install -r ./.circleci/requirements.txt
      - run: ansible-lint ./tests/test.yml
      - run: ansible-playbook ./tests/test.yml --syntax-check