---
- name: restart_service_nginx
  service:
    name: nginx
    state: restarted
  when: nginx_restart | bool

- name: restart_docker_nginx
  docker_compose:
    project_src: "{{ nginx_docker_dir }}"
    services: ["{{ nginx_docker_name }}"]
    restarted: yes
  when: nginx_restart | bool